### ISSUE TITLE
Enhance current packaging method

### ISSUE THREAD

**Issue by gromdimon** [bihealth/auto-acmg#26]
**Is your feature request related to a problem? Please describe.**
We use setuptools for packaging autopvs1. However, we use a simple `pyproject.toml` setup, when we probably should use more advanced options (setup.cfg and setup.py) for dynamic versioning and similar staff.

**Describe the solution you'd like**
- Investigate upgrade options (what to include)
- Implement!

**Describe alternatives you've considered**
N/A

**Additional context**
List of possible enhancements:
- Dynamic versioning
- Automatic github package publishing
- Add `Changelog.md`

**Comment by holtgrewe** [comment]
Setup.py is deprecated.

**Comment by gromdimon** [comment]
Was implemented in #90
