### ISSUE TITLE
Specify variants used for development and testing

### ISSUE THREAD

**Issue by gromdimon** [bihealth/auto-acmg#34]
**Is your feature request related to a problem? Please describe.**
We need to maintain the list of variants, which are used for development and testing. This ensures, that our software works properly (at least for this variants) and also adresses issues if theese happen.

**Describe the solution you'd like**
Add variants in file `example_variants.txt`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by gromdimon** [comment]
In #33 some variants were added. However, we need to enlarge this list

**Comment by xiamaz** [comment]
Hey, if you haven't added them. Here are some more: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6185798/bin/NIHMS986839-supplement-Supp_TableS1.pdf

**Comment by gromdimon** [comment]
Yeah, I think my first PR was based on these variants :) 
However, I used alternative table link: https://onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1002%2Fhumu.23626&file=humu23626-sup-0001-tableS1.xlsx
